# These are supported funding model platforms

github: davidcraig # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: privatesniper
open_collective: # Replace with a single Open Collective username
ko_fi: privatesniper
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
